import { GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";
import Router from "next/router";
import { Navbar } from "../components/navbar";

import AvailableItem from "../components/availableItem";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  const merchantId = sessionData?.user?.id as string;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#e0cbac] to-[#ffffff]">
        <Navbar
          role={sessionData?.user?.role}
          profileSrc={sessionData?.user?.image}
        />
        <AvailableItem />
      </main>
    </>
  );
};

export default Home;
